import fs from 'node:fs/promises';
import {loadRuntimeConfig} from '../../src/lib/config.js';
import {loadProjectConfig} from '../../src/lib/project-config.js';
import {describe, expect, it} from 'vitest';
import {TerminalSession} from './support/terminal-session.js';
import {
  createPhase4InitFixture,
  removeTempPaths,
  type Phase4InitFixture
} from './support/test-env.js';

describe('init terminal e2e', () => {
  it('drives the interactive init wizard and writes repo-local Shrike config', async () => {
    let fixture: Phase4InitFixture | null = null;
    let session: TerminalSession | null = null;

    try {
      fixture = await createPhase4InitFixture();

      session = TerminalSession.spawn({
        command: fixture.commandPath,
        args: ['init'],
        cwd: fixture.repoRoot,
        env: fixture.env,
        cols: 120,
        rows: 40
      });

      await session.waitForText('OpenCode discovery', {
        source: 'screen',
        timeoutMs: 60_000
      });
      await session.waitForIdleFrame({
        idleMs: 200,
        timeoutMs: 10_000
      });

      const discoveryScreen = await session.screen();
      expect(discoveryScreen).toContain('OpenCode discovery');
      expect(discoveryScreen).toContain('azure/gpt-5.4-mini');
      expect(discoveryScreen).toContain('Continue with discovered OpenCode setup');

      session.press('down');
      session.press('up');
      session.press('enter');

      await session.waitForText('Select default scan model', {
        source: 'screen',
        timeoutMs: 30_000
      });
      session.press('enter');

      await session.waitForText('Select default fix model', {
        source: 'screen',
        timeoutMs: 30_000
      });
      session.press('enter');

      await session.waitForText('Select default policies', {
        source: 'screen',
        timeoutMs: 30_000
      });
      session.press('enter');

      await session.waitForText('Setup complete', {
        source: 'screen',
        timeoutMs: 30_000
      });
      await session.waitForIdleFrame({
        idleMs: 200,
        timeoutMs: 10_000
      });

      const completedScreen = await session.screen();
      expect(completedScreen).toContain('Setup complete');
      expect(completedScreen).toContain(fixture.selectedScanModel);
      expect(completedScreen).toContain(fixture.selectedFixModel);
      expect(completedScreen).toContain(fixture.expectedPolicyId);

      session.press('down');
      await session.waitForText('\u25cf  Change saved defaults', {
        source: 'screen',
        timeoutMs: 5_000
      });
      session.press('down');
      await session.waitForText('\u25cf  Exit', {
        source: 'screen',
        timeoutMs: 5_000
      });
      session.press('enter');

      const exit = await session.waitForExit(30_000);
      expect(exit.exitCode).toBe(0);

      const projectConfig = await loadProjectConfig(fixture.projectConfigPath);
      const runtimeConfig = await loadRuntimeConfig(fixture.repoOpencodeConfigPath, {
        agent: 'shrike-checker',
        model: fixture.selectedScanModel
      });
      const seededCheckFiles = await fs.readdir(fixture.checksDirectory);

      expect(projectConfig.config.init.opencodeSetup).toBe('existing-config');
      expect(projectConfig.config.init.seedPolicyId).toBe(fixture.expectedPolicyId);
      expect(projectConfig.config.init.seedPolicyIds).toEqual([fixture.expectedPolicyId]);
      expect(projectConfig.config.runtime.scanModel).toBe(fixture.selectedScanModel);
      expect(projectConfig.config.runtime.fixModel).toBe(fixture.selectedFixModel);
      expect(projectConfig.config.runtime.mode).toBe('native');
      expect(projectConfig.config.scan.defaultKind).toBe('project-checks');
      expect(projectConfig.config.scan.defaultId).toBe('.openshrike/checks');

      expect(runtimeConfig.config.model).toBe(fixture.selectedScanModel);
      expect(runtimeConfig.config.agent?.['shrike-checker']?.model).toBe(fixture.selectedScanModel);
      expect(runtimeConfig.config.agent?.['shrike-fixer']?.model).toBe(fixture.selectedFixModel);

      await expect(fs.readFile(fixture.readmePath, 'utf8')).resolves.toContain('This directory is generated by `shrike init`.');
      expect(seededCheckFiles.length).toBeGreaterThan(0);
      expect(seededCheckFiles.every(fileName => fileName.endsWith('.md'))).toBe(true);
    } finally {
      await session?.close();
      if (fixture) {
        await removeTempPaths(fixture.tempPaths);
      }
    }
  });
});
