import fs from 'node:fs/promises';
import path from 'node:path';
import {resolveCheckDefinitionPath} from '../checks.js';
import {buildDefaultOpencodeConfig, serializeConfig} from '../config.js';
import {
  CONFIG_DIRECTORY_NAME,
  CONFIG_FILE_NAME,
  DEFAULT_AGENT_NAME,
  DEFAULT_OUTPUT,
  DEFAULT_PARALLELISM,
  DEFAULT_RUNTIME_MODE,
  DEFAULT_SCAN_SCOPE,
  INIT_README_FILE_NAME,
  PROJECT_CHECKS_DIRECTORY_NAME,
  PROJECT_CONFIG_FILE_NAME
} from '../constants.js';
import {resolvePolicyDefinition} from '../policies.js';
import {serializeProjectConfig, writeProjectConfig} from '../project-config.js';
import type {ProjectType, RuntimeMode, ShrikeProjectConfig} from '../types.js';

export interface InitWriteOptions {
  repoRoot: string;
  policyId: string;
  model?: string | undefined;
  runtimeMode?: RuntimeMode | undefined;
  projectType: ProjectType;
  detectedFrom: string[];
  opencodeSetup: 'existing-config' | 'auth-login';
}

export interface InitWriteResult {
  configDirectory: string;
  checksDirectory: string;
  opencodeConfigPath: string;
  projectConfigPath: string;
  readmePath: string;
  seededCheckPaths: string[];
  projectConfig: ShrikeProjectConfig;
}

export async function writeShrikeInitFiles(options: InitWriteOptions): Promise<InitWriteResult> {
  const configDirectory = path.join(options.repoRoot, CONFIG_DIRECTORY_NAME);
  const checksDirectory = path.join(configDirectory, PROJECT_CHECKS_DIRECTORY_NAME);
  const opencodeConfigPath = path.join(configDirectory, CONFIG_FILE_NAME);
  const projectConfigPath = path.join(configDirectory, PROJECT_CONFIG_FILE_NAME);
  const readmePath = path.join(configDirectory, INIT_README_FILE_NAME);
  const projectConfig = buildShrikeProjectConfig({
    policyId: options.policyId,
    model: options.model,
    runtimeMode: options.runtimeMode ?? DEFAULT_RUNTIME_MODE,
    projectType: options.projectType,
    detectedFrom: options.detectedFrom,
    opencodeSetup: options.opencodeSetup
  });

  await fs.mkdir(configDirectory, {recursive: true});
  await fs.mkdir(checksDirectory, {recursive: true});
  await fs.writeFile(
    opencodeConfigPath,
    `${serializeConfig(buildDefaultOpencodeConfig(options.model))}\n`,
    'utf8'
  );
  await writeProjectConfig(projectConfigPath, projectConfig);
  const seededCheckPaths = await seedProjectChecksDirectory({
    checksDirectory,
    policyId: options.policyId
  });
  await fs.writeFile(
    readmePath,
    buildInitReadme({
      checksDirectory,
      projectConfigPath,
      opencodeConfigPath
    }),
    'utf8'
  );

  return {
    configDirectory,
    checksDirectory,
    opencodeConfigPath,
    projectConfigPath,
    readmePath,
    seededCheckPaths,
    projectConfig
  };
}

export function buildShrikeProjectConfig(options: {
  policyId: string;
  model?: string | undefined;
  runtimeMode: RuntimeMode;
  projectType: ProjectType;
  detectedFrom: string[];
  opencodeSetup: 'existing-config' | 'auth-login';
}): ShrikeProjectConfig {
  return {
    $schema: 'https://openshrike.dev/schema/project.json',
    version: 1,
    init: {
      projectType: options.projectType,
      detectedFrom: options.detectedFrom,
      opencodeSetup: options.opencodeSetup,
      seedPolicyId: options.policyId
    },
    runtime: {
      configPath: path.posix.join(CONFIG_DIRECTORY_NAME, CONFIG_FILE_NAME),
      agent: DEFAULT_AGENT_NAME,
      ...(options.model ? {model: options.model} : {}),
      mode: options.runtimeMode,
      parallelism: DEFAULT_PARALLELISM
    },
    scan: {
      defaultKind: 'project-checks',
      defaultId: path.posix.join(CONFIG_DIRECTORY_NAME, PROJECT_CHECKS_DIRECTORY_NAME),
      repo: '.',
      scope: DEFAULT_SCAN_SCOPE,
      output: DEFAULT_OUTPUT,
      ui: true,
      artifactsDir: null
    }
  };
}

export function buildInitReadme(options?: {
  checksDirectory?: string | undefined;
  projectConfigPath?: string | undefined;
  opencodeConfigPath?: string | undefined;
}): string {
  const checksLabel = path.basename(options?.checksDirectory ?? PROJECT_CHECKS_DIRECTORY_NAME);
  const projectConfigLabel = path.basename(options?.projectConfigPath ?? PROJECT_CONFIG_FILE_NAME);
  const opencodeConfigLabel = path.basename(options?.opencodeConfigPath ?? CONFIG_FILE_NAME);

  return [
    '# OpenShrike Init',
    '',
    'This directory is generated by `shrike init`.',
    '',
    `- \`${checksLabel}/\` stores the project-local Markdown checks that Shrike executes.`,
    `- \`${projectConfigLabel}\` stores repo-local Shrike defaults such as the selected policy and scan settings.`,
    `- \`${opencodeConfigLabel}\` is a Shrike-owned OpenCode overlay for read-only scans.`,
    '- User-global OpenCode config and credentials remain outside this repository.',
    '',
    'Re-run `shrike init` to seed additional checks from a different policy or choose a different model/runtime.',
    'After initialization, `shrike scan` reads only Markdown checks from `checks/`.'
  ].join('\n') + '\n';
}

export function serializeShrikeProjectConfig(config: ShrikeProjectConfig): string {
  return serializeProjectConfig(config);
}

async function seedProjectChecksDirectory(options: {
  checksDirectory: string;
  policyId: string;
}): Promise<string[]> {
  const policy = await resolvePolicyDefinition(options.policyId);
  const seededPaths: string[] = [];

  for (const checkId of policy.checkIds) {
    const sourcePath = await resolveCheckDefinitionPath(checkId);
    const targetPath = path.join(options.checksDirectory, path.basename(sourcePath));
    const targetStats = await fs.stat(targetPath).catch(error => isNotFoundError(error) ? null : Promise.reject(error));

    if (targetStats?.isDirectory()) {
      throw new Error(`Cannot seed check '${checkId}' because '${targetPath}' is a directory.`);
    }

    if (!targetStats) {
      const definition = await fs.readFile(sourcePath, 'utf8');
      await fs.writeFile(targetPath, ensureTrailingNewline(definition), 'utf8');
    }

    seededPaths.push(targetPath);
  }

  return seededPaths;
}

function ensureTrailingNewline(value: string): string {
  return value.endsWith('\n') ? value : `${value}\n`;
}

function isNotFoundError(error: unknown): boolean {
  return (error as NodeJS.ErrnoException)?.code === 'ENOENT';
}
