import fs from 'node:fs/promises';
import path from 'node:path';
import {buildDefaultOpencodeConfig, serializeConfig} from '../config.js';
import {
  CONFIG_DIRECTORY_NAME,
  CONFIG_FILE_NAME,
  DEFAULT_AGENT_NAME,
  DEFAULT_OUTPUT,
  DEFAULT_PARALLELISM,
  DEFAULT_RUNTIME_MODE,
  DEFAULT_SCAN_SCOPE,
  INIT_README_FILE_NAME,
  PROJECT_CONFIG_FILE_NAME
} from '../constants.js';
import {serializeProjectConfig, writeProjectConfig} from '../project-config.js';
import type {ProjectType, RuntimeMode, ShrikeProjectConfig} from '../types.js';

export interface InitWriteOptions {
  repoRoot: string;
  policyId: string;
  model?: string | undefined;
  runtimeMode?: RuntimeMode | undefined;
  projectType: ProjectType;
  detectedFrom: string[];
  opencodeSetup: 'existing-config' | 'auth-login';
}

export interface InitWriteResult {
  configDirectory: string;
  opencodeConfigPath: string;
  projectConfigPath: string;
  readmePath: string;
  projectConfig: ShrikeProjectConfig;
}

export async function writeShrikeInitFiles(options: InitWriteOptions): Promise<InitWriteResult> {
  const configDirectory = path.join(options.repoRoot, CONFIG_DIRECTORY_NAME);
  const opencodeConfigPath = path.join(configDirectory, CONFIG_FILE_NAME);
  const projectConfigPath = path.join(configDirectory, PROJECT_CONFIG_FILE_NAME);
  const readmePath = path.join(configDirectory, INIT_README_FILE_NAME);
  const projectConfig = buildShrikeProjectConfig({
    policyId: options.policyId,
    model: options.model,
    runtimeMode: options.runtimeMode ?? DEFAULT_RUNTIME_MODE,
    projectType: options.projectType,
    detectedFrom: options.detectedFrom,
    opencodeSetup: options.opencodeSetup
  });

  await fs.mkdir(configDirectory, {recursive: true});
  await fs.writeFile(
    opencodeConfigPath,
    `${serializeConfig(buildDefaultOpencodeConfig(options.model))}\n`,
    'utf8'
  );
  await writeProjectConfig(projectConfigPath, projectConfig);
  await fs.writeFile(
    readmePath,
    buildInitReadme({
      projectConfigPath,
      opencodeConfigPath
    }),
    'utf8'
  );

  return {
    configDirectory,
    opencodeConfigPath,
    projectConfigPath,
    readmePath,
    projectConfig
  };
}

export function buildShrikeProjectConfig(options: {
  policyId: string;
  model?: string | undefined;
  runtimeMode: RuntimeMode;
  projectType: ProjectType;
  detectedFrom: string[];
  opencodeSetup: 'existing-config' | 'auth-login';
}): ShrikeProjectConfig {
  return {
    $schema: 'https://openshrike.dev/schema/project.json',
    version: 1,
    init: {
      projectType: options.projectType,
      detectedFrom: options.detectedFrom,
      opencodeSetup: options.opencodeSetup
    },
    runtime: {
      configPath: path.posix.join(CONFIG_DIRECTORY_NAME, CONFIG_FILE_NAME),
      agent: DEFAULT_AGENT_NAME,
      ...(options.model ? {model: options.model} : {}),
      mode: options.runtimeMode,
      parallelism: DEFAULT_PARALLELISM
    },
    scan: {
      defaultKind: 'policy',
      defaultId: options.policyId,
      repo: '.',
      scope: DEFAULT_SCAN_SCOPE,
      output: DEFAULT_OUTPUT,
      ui: true,
      artifactsDir: null
    }
  };
}

export function buildInitReadme(options?: {
  projectConfigPath?: string | undefined;
  opencodeConfigPath?: string | undefined;
}): string {
  const projectConfigLabel = path.basename(options?.projectConfigPath ?? PROJECT_CONFIG_FILE_NAME);
  const opencodeConfigLabel = path.basename(options?.opencodeConfigPath ?? CONFIG_FILE_NAME);

  return [
    '# OpenShrike Init',
    '',
    'This directory is generated by `shrike init`.',
    '',
    `- \`${projectConfigLabel}\` stores repo-local Shrike defaults such as the selected policy and scan settings.`,
    `- \`${opencodeConfigLabel}\` is a Shrike-owned OpenCode overlay for read-only scans.`,
    '- User-global OpenCode config and credentials remain outside this repository.',
    '',
    'Re-run `shrike init` to refresh detected defaults or choose a different model/policy.',
    'After initialization, `shrike scan` will use these saved defaults automatically.'
  ].join('\n') + '\n';
}

export function serializeShrikeProjectConfig(config: ShrikeProjectConfig): string {
  return serializeProjectConfig(config);
}
